version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  app:
    image: sand050965/taipei-day-trip
    container_name: app
    expose:
      - 8080
    env_file: ./.env
    restart: on-failure